# Generated by Django 5.0.6 on 2026-06-23 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('iqama_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='يرجى إدخال رقم إقامة صحيح يتكون من 10 أرقام.', regex='^\\d{10}$')], verbose_name='رقم الإقامة')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='يرجى إدخال رقم جوال سعودي صحيح يبدأ بـ 05 ويتكون من 10 أرقام.', regex='^05\\d{8}$')], verbose_name='رقم التواصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'طلب انضمام',
                'verbose_name_plural': 'طلبات الانضمام',
                'ordering': ['-created_at'],
            },
        ),
    ]
